index:
    path: /
    controller: App\Controller\DefaultController::index

article:
    path: /article
    controller: App\Controller\ArticleController::index

newArticle:
    path: /article/new
    controller: App\Controller\ArticleController::new

addImageArticle:
    path: /article/add_image
    controller: App\Controller\ArticleController:add_image_page

addImageAction:
    path: /article/add_image_action
    controller: App\Controller\ArticleController:add_image_action
