index:
    path: /
    controller: App\Controller\DefaultController::index

article:
    path: /article
    controller: App\Controller\ArticleController::index

newArticle:
    path: /article/new
    controller: App\Controller\ArticleController::new